name: typescript-action
description: Template of TypeScript Action

inputs:
  message:
    description: |
      The message to use for the changeset.
    required: true
  commit-message:
    description: |
      The commit message to use.
    default: "create changeset for renovate"
  dry-run:
    description: |
      Whether to run in dry-run mode.
    default: "false"
  working-directory:
    description: |
      The working directory to use.
    default: "."
  pnpm-workspace:
    description: |
      The pnpm workspace to use.
    default: "false"
  github-token:
    description: |
      The GitHub token to use.
    required: true

runs:
  using: composite
  steps:
    - uses: technote-space/get-diff-action@f27caffdd0fb9b13f4fc191c016bb4e0632844af # v6.1.2
      id: git-diff

    - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: 20.19.5

    - shell: sh
      working-directory: ${{ inputs.working-directory }}
      env:
        diff: ${{ steps.git-diff.outputs.diff }}
        message: ${{ inputs.message }}
        dry_run: ${{ inputs.dry-run }}
        pnpm_workspace: ${{ inputs.pnpm-workspace }}
      run: node ${{ github.action_path }}/dist/main.js

    - uses: int128/update-generated-files-action@cb476932f792a2cc2409c6d2af6db9d39f5e296b # v2.62.0
      if: inputs.dry-run == 'false'
      with:
        token: ${{ inputs.github-token }}
        commit-message: ${{ inputs.commit-message }}
