name: release

on:
  pull_request:
    paths:
      - .github/workflows/release.yaml
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/create-github-app-token@21cfef2b496dd8ef5b904c159339626a10ad380e # v1.11.6
        id: app-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ steps.app-token.outputs.token }}
      - uses: ./.github/actions/setup
        with:
          token: ${{ steps.app-token.outputs.token }}
          bot-app-slug: ${{ steps.app-token.outputs.app-slug }}

      - run: pnpm i
      - run: pnpm build

      - uses: YutaUra/typescript-changeset-release-action@f05420667fb207beadec7b28bcf12e38029ede42 # v0.1.2
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        with:
          setup-git-user: false
          auto-merge: true
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
